import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useEffect } from 'react';
import styles from '../styles/Home.module.css';
import { useUser } from '@hooks/useUser';

const Home: NextPage = () => {
  const { user } = useUser();

  return (
    <div className="min-h-screen flex justify-center items-center h-screen flex-col">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex justify-center items-center h-full w-full flex-col">
        {user && (
          <>
            <strong>{user.name}</strong>
            <div>{user.permission}</div>
          </>
        )}
      </main>
    </div>
  );
};

export default Home;
